name: Tag on Merge

on:
  push:
    branches: [ "master" ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Determine new version
        id: version
        run: |
          # Fetch the latest tags
          git fetch --tags

          # Get the latest tag or set to default if no tags are found
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0.0")
          echo "Latest tag: $LATEST_TAG"

          # Remove the 'v' prefix if present
          LATEST_TAG="${LATEST_TAG#v}"

          # Split the version into an array
          IFS='.' read -ra VERSION_PARTS <<< "$LATEST_TAG"

          # Initialize version parts
          MAJOR=${VERSION_PARTS[0]:-0}
          MINOR=${VERSION_PARTS[1]:-0}
          PATCH=${VERSION_PARTS[2]:-0}
          BUILD=${VERSION_PARTS[3]:-0}

          # Get the commit messages from the last commit
          COMMITS=$(git log --format=%B -n 1 HEAD)
          echo "Commit messages: $COMMITS"

          # Determine version increment based on commit messages
          if echo "$COMMITS" | grep -q '^MAJOR:'; then
            ((MAJOR++))
            MINOR=0
            PATCH=0
            BUILD=0
          elif echo "$COMMITS" | grep -q '^MINOR:'; then
            ((MINOR++))
            PATCH=0
            BUILD=0
          elif echo "$COMMITS" | grep -E -q '^(feat|fix|feature|bug|chore|refactor):'; then
            ((PATCH++))
            BUILD=0
          else
            ((BUILD++))
          fi

          # Output the new version
          NEW_TAG="v$MAJOR.$MINOR.$PATCH.$BUILD"
          echo "New tag: $NEW_TAG"
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Create and push new tag
        run: |
          # Check if the new tag already exists
          if git rev-parse "refs/tags/${{ steps.version.outputs.new_tag }}" >/dev/null 2>&1; then
            echo "Tag already exists. Exiting."
            exit 0
          fi

          git tag ${{ steps.version.outputs.new_tag }}
          git push origin ${{ steps.version.outputs.new_tag }}
